router bgp 65000
bgp router-id 10.52.10.1

neighbor 10.52.10.82 remote-as 65001
neighbor 10.52.10.82 description K8S-NODE-01

neighbor 10.52.10.32 remote-as 65001
neighbor 10.52.10.32 description K8S-NODE-02

neighbor 10.52.10.51 remote-as 65001
neighbor 10.52.10.51 description K8S-NODE-03

address-family ipv4

neighbor 10.52.10.82 activate
neighbor 10.52.10.82 soft-reconfiguration inbound
neighbor 10.52.10.82 route-map K8S-LB-IN in

neighbor 10.52.10.32 activate
neighbor 10.52.10.32 soft-reconfiguration inbound
neighbor 10.52.10.32 route-map K8S-LB-IN in

neighbor 10.52.10.51 activate
neighbor 10.52.10.51 soft-reconfiguration inbound
neighbor 10.52.10.51 route-map K8S-LB-IN in

exit-address-family
exit

! Only accept the Kubernetes LoadBalancer VIP 

route-map K8S-LB-IN permit 10
match ip address prefix-list K8S-LB
exit

ip prefix-list K8S-LB seq 10 permit 10.52.30.0/24 le 32