apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-route
  namespace: longhorn-system
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
      # match all is no hostnames
  hostnames:
    - "lh.kube.ruitenbeek.dev"
  rules:
    - backendRefs:
        - name: longhorn-frontend
          port: 80