---
apiVersion: v1
kind: Service
metadata:
  name: ldap-home
  namespace: default
  labels:
    advertise: bgp
spec:
  type: LoadBalancer
  selector:
    goauthentik.io/outpost-name: ldap-home
  ports:
    - name: ldap
      port: 389
      targetPort: 6636
      protocol: TCP
