apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault-route
  namespace: default
spec:
  parentRefs:
    - name: shared-gateway
      namespace: default
  hostnames:
    - "vault.kube.ruitenbeek.dev"
  rules:
    - backendRefs:
        - name: vaultwarden
          port: 80