apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:VeMuS0+cNg7SPEpMjk7Brj55u2ghxY/B/IG5A4Z8Pc+GlQuy9ONAbA==,iv:cwGYSDnxG5zDpE3KDNLz9U9dyhKmJ04yDEtRFpM19tg=,tag:iRmhwmqLPwkBOK/U7SshMA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T10:15:27Z"
    mac: ENC[AES256_GCM,data:Vr2Anfd7e86ptacsjloZspomCVWKStx4O7KeVXtw9tClFHU7RbIXWiRCeRzK5OP+xEpDxOYeIaXWyICLxtHk8/X+m3CNxG0mZX7nZPoUnziRIdjApzj33aBwEVhzJuR9dB2RWreI3oDFSTYa2NZZ1Jq/gUk7OUbytCHeCitlrSc=,iv:XpJ5g53AGjOj8g9ganbGw/3JfuQPlBA7uIUiveftkfI=,tag:mdv5U7dEI22lEWiaUqLVBQ==,type:str]
    pgp:
        - created_at: "2026-09-21T10:15:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9/tRI0Ckh/2AQ/+PaLz13cNMrBNehEcvv4wkAcjhT5ShFZW/y2ABWDOY57X
            3vzV9RDz87HWk4oCJbMUmYp10+F/neMOG+LxbAaXRbEZo67iZg9NhdUq81l13O1G
            LpwXD/dMM3nxMx3F8GeoXCKmR/jFh3r//DmwLHmqDVhrZuPkKUvieVww6LZgmNOX
            5Ti757NRmr4Ctz5m7sFTdFDQW6oWW0jrrKMUwrswgx2u1KO6zXxg49slezYxnW6p
            HBxfkJ0VUjPhdArfq0lh2eh7lt6IPrW5tBSGKg8qjvaU+ccQ1mvlrPhF+zxnrFaY
            AS1/4GqHiV2X8q0IXDVn0ssDhP1CVO8RFPNI2v0ZvfXRyTB6jvjO776WUOoH537N
            P3fn2RnEObqYYbkiI+56aJyQprDADZEcPBGPJY+FowRa8j29SmnLx06kl2VQUlkT
            YtY7X/bX4sPif37u+VqNX9LR8uyk+FsRSwg2f6tN1qppxNx5lopouU+xvtCMaj3l
            epng6f5W1yO8v5InvzsKRSfC2oHN0bnWlFcr82ywdnXXH3pz2v9ocMimRK5BPQbK
            3l2LhnDFA7S3tVFuYi4i38ew7TCUUwAZf+jUhEfvOkcN2f2oolXjsMra9JImsZM2
            MFRN6P3BXDqneeao8Hq2vih4meka6y1D7F+Dj5oFWXsyzgWfLdy2oNpL/8R9ZzHS
            XgGbgkQt0GPe7fjWYfqsdvQBaaA7FkuyVN4t7AMJAgklKOViQFukVEKS9L6/ZrXO
            x6i8sYcbJ1jI4iH6/X0qCXMx+UZNeSt5FPFK4xzHNY/E84V/z9ID+ssuURlS2Lo=
            =z9VK
            -----END PGP MESSAGE-----
          fp: DDBB778AB55A1D87205700CBDDA211F23723E463
    version: 3.13.3
