apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: default
type: Opaque
stringData:
    zip_password: ENC[AES256_GCM,data:bC5yPfRM78+EFEfFUlc4/wn0TNGLY1nA2rN/xoja7vCt7a/hTkK4Knw2MlDfclfU,iv:P54yYABs71p9HdEi96dR/+nec6mmpN8hrk1Uphaz8I0=,tag:UOvSfvjhGA6BBMIUJRqO4A==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T09:20:15Z"
    mac: ENC[AES256_GCM,data:BdC2/JX50itmseoo/0VbKDqa3xo4cgqQdsqJXlCqtkYwQ3IfgULoihir56IuvDpZr1tFQJLCtdOiCYKNBrYhoz51vIA0ak4bv0GU0/BJZIEw8PGslwu+Sbpp3wtyuDR9CA3X7OUOlmWt/w8XtcJ5IJeOngyyfgUf1HTfZg9JWGY=,iv:gWY/Wg3iKccS5M2vtL6ps3UElw1e4OiSHwLl8Hbt3Ko=,tag:eP+eoTyPWAi+qZiVlvrBAQ==,type:str]
    pgp:
        - created_at: "2026-09-24T09:20:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9/tRI0Ckh/2AQ//W6m1t4ewi9oZMmaXgZCOd6PET7vg7lXe79GAuEJrvyyt
            roA2zsiIKoKSdg+oOr2EQ99uWK+sFw23gAqtDoGTe68OALGizNRghY2uAgAXGMRa
            q1DgDu0RGkNxDw8RaShLUBpw25kLtw4RUd5hKvlK8+95NbrM0j2hoDB04IYdPVPV
            ryhl2x2OE20IcRUqXxLggxJBPoxD/2p3JdMOYx7qe0Cq8mXwMKhrUowBBHIbQf30
            PV3UteuMkjaWRzeEia5VdPJFD3DWwqs7oonyTRY1KGPdd0RoaA8WqA6E3FdhU7hQ
            Yjykk7r/ALtTi3reZKk88/vf6oHx0RGkqMv45FF2w9pxy7sXGYLtYrImL7BmB1kK
            u913/i2cJ0wbA7DSi/0RtppMTNlOe631PiAF1hl0Unt+GYareU4qm28SsXCNnwDj
            jXRK0S1Eko+1kf1UVVdMbSc+VUMz9DenAQY647RK8SY+3Q/nZ4vXgeM3V2i0cLgW
            M9kc5SHYo0xkIJAKR0v6DqKaBK/eM+LemWfFOUq6VHfBSKbkSW25YRoIcM/BEmzx
            cx54BYN4SN9uqnNEvHucFv2kH6Y28NW7Qn3OaCSwbmAFrp4mtbSZbRcK2nSyFTLu
            K9PESqOYZFptfjob6Js6TdbIBUaiEXbaIl6cKISn7fAn4pTQzeGjlt2kxpv1mtjS
            XAEOyPBfXc8WIG9cr+HPN4RtW7cmSa5cwXsQlgyZ1o4sgEvTeVS2ugvzolc8uRH2
            HmUM7G2VSNw6TFBe8xCokFtxSQwpaTRCHdVaFPnjAOYPs6xxmNfl3ynJyw1u
            =wncn
            -----END PGP MESSAGE-----
          fp: DDBB778AB55A1D87205700CBDDA211F23723E463
    version: 3.13.3
