apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-admintoken
    namespace: default
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:J0hqaFGRO9VIHktsfabJZFj2IgWLW61EF5jy+T9+Lt6zAoH7utEpcGK8BCYKIgC4,iv:yHmDae6b9a29xqfRPlwe08qhS/SzllTE/+ouJ4s8zKw=,tag:+ZNo4jNqGdp3gwzwpW7rSA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T09:00:53Z"
    mac: ENC[AES256_GCM,data:HPe7lGOcCYpgSYPrCGAfckXdu2BqxW0IVpCG+GkRTsGOy1RWOe3s8dnx0ilqCD660U1ZlSu/T8oX7IkBdAYzjQC4F/esmdN6OCz73j4S4SYq4bil0qAkc2GMGyIyk5aLgOr0p1cfMwi9rU85JTNdAzXnGAXpliWtjeGfyzG6Nm4=,iv:aLL7zkHUNXah7cGAwG+iy/3kNZ6qOH63++0nMGZjQzk=,tag:QF9k16SltVZjcVhmcKnxHQ==,type:str]
    pgp:
        - created_at: "2026-09-24T09:00:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9/tRI0Ckh/2ARAA6VbLkYI4w5GAyc8ss+9StOwh/r75rH+8lfNHIanT50th
            A5K3qF+J3v/7j4ShGGpjag4sZgzsm0HWrRs0Gw/aoSq6v5fRsuGZUZtyoieBn4p1
            WuwXayT5Vnq/hURFVlyVZNaO+CywqGqyswl36ob/zo+JMru21SkU2iaZYMFgBnV0
            /ODvav2JKHiRDCUES/1xizB9o2J4/BrjnM+7HAaiPS1IE90gGASkJmj+8b6bXzf7
            9X6XbMtrdS7c14QByARSHdg1+89MT5CeOv2rkO+Wv7kMKg+5bCNz64uOMPJtUhw6
            +Wd+MdrMEUKcxyfD140653T9UWjw2JZAABP1U+nhjqHOWFYI35GpdGRGrD21Mj5J
            i6/qhbjDQYki6dZ+4YItFlQWeN4+UEZD/2cenFUEnFZXjbMO956K43OXbmTW5R5F
            NJhNsF3ONIkelbT+IM9Zu9O8l+eddspmt+ffSYeFCKZ16IDmI5VdC5EdDGU9u7ff
            EuLr4aMDMlu4deMzjPdixvI2JpBYBKyL6E+iC1KBMHOIAUxOBhPWJLhGOXv0JD0i
            1SRBQ+V/DHfi9kZysB2g62N9Eayft6EAsfEtF0y64nwwPiwyJuH8MrqNc0J41J9T
            j05r2ZgjfzuJUKQW8ZRo4khlwJxQ6AuwFnIurpD2fJnKQIcwplCnLpogkTpsgjbS
            XgGRRaMxqOJBUrFsRCHwHjlvPSnuzavTY7dDmSDIYyeLWE+LzBek8cjhac0QnSXF
            6VL0gsw7ES8b2or2KSTyNM5VjRryyOrdJRaZefjj9/4JOB1RUz/97hBdpEqy7LY=
            =NAve
            -----END PGP MESSAGE-----
          fp: DDBB778AB55A1D87205700CBDDA211F23723E463
    version: 3.13.3
