apiVersion: v1
kind: Secret
metadata:
    name: vw-rclone-config
    namespace: default
type: Opaque
stringData:
    rclone.conf: ENC[AES256_GCM,data:QOsF1FLV7evzmNMstAXDvoleyH0/AvgSj1Fkaric9hc7J5wBEJp9lWlXaNtR1w7RcbbqeLJvoHTqOuMwoivZuArUsPsHD6PHE3qHNFUkif7DKfNihe3/CXSXZUogTw5OE9/9MikUN+Pr3Vd502rIpJFFsitjStdtecxLX10L4rwjtD5+jcvnwy1CY+g/669u0w0Ivid9CoWIGKyqXrKNNCBS5dgVeiMVIZqBv1QOB9t3PWm0VGSht/f+vcg5Zt+vhd13ebPhvAaeFG6oUGX+BjXkeUKD7rkCGOWKWyjJYvMelSRbkypGTm0wC5LL4LqVRp2JldUj12ALtUIS9UoaPOFxLglDuYPmtqukmOx781hL2vG1pxmP,iv:0tiGwe2Y/QoV8E0o/Oow2PbANkS9rEQNpeHs/9fCTCU=,tag:ty794jqAlcRTH1lDDhryCQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T18:19:56Z"
    mac: ENC[AES256_GCM,data:OiWLoOA1i0PMgE+E1+0sLsPyiu/gYsSxIgkf9qNbEaQXaXj1yaQvsDPGNCtMQYZ6V4rXdcQP06lUC6bbrq+DmPAWe2aIqR6A3gJjdPwI0/TPd3Vn1KUSfd12M0NniRYad7EoRgfB2AcqdRB1pOkipWafhg2p9ejPZs1bbt5l+kA=,iv:M3EGXzeB+3aw6LudFo1rBr8uac3Zv5N0utAcI03KvRc=,tag:GwFTVUsk30Driw0xHGEuTQ==,type:str]
    pgp:
        - created_at: "2026-09-24T18:19:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9/tRI0Ckh/2ARAAluM49PshJtXoVjW5YAQn5ZtnwdUVG+DxnD0XINLosHCz
            80Ns+FFQEWJOisDWG851CBZ5fZhpcHJsXNGPcAOI+q1BGI94reFK5xN16fTb0wlm
            CHLZc4v8353je6hG+ZlUQa6M8n3LCsGhEEuuaLdDz2+RklumJjTRb76kj8aVnEcP
            hd6O1nAxlKHsTQyQwBQrYFJgO2iKSlfBKHs+gorrjDTPv8/f4LiIvCNrxbZfEr4l
            ko+rRCxEvmXEO+mmCQb76yE5ldag8yNjEYBCwCb7SOISOYSeRfWBh7U+5gozQRG6
            KTIyTUoX6pT0vAiDovsq+R8ytCBLXL3eJ2sXk6H9/RH9Fbm1Pt7wIE1/9/yn/1Nl
            Xa9kyzo3PyaRMD6KvVBzXMgA59jG1mGFp4qy2iuFHj4384sCwOkJ+BzvY4iAs/xE
            BAEvf0eDeTTSmFCdznzOyIyp6Xvv+JgENX/Kw9hPuGRTt3VPGCnMmcnUj82W2Jyl
            lvPy+iFpTel1KDpJEhGiNHq5IAJToYf3Yy3oXr6l/Ho2c3Pj8owsmq+PTmAsephB
            k3wCvrgw0rUxby5YBDCOLONlDlnpq4OY8n+iNtd/abOfCFfDoMjIGCcLEcIfC4gr
            CGdUEssMSU8IXgcsra3g5ssPIsIe/Ztm8EHfQVj6BmdUy8F3WsV6yFJSmF0ZVlHS
            XgEKQ9S1XBu9OI7E3otUD2kbSdZ1om8pBjNvEzO6PVSReLwX6piDvjnOOCbYvQvJ
            MkNpCP3s3AR7BWQ3JkdAugdWIbxBd6GviSEQ97FJaHf4yFFmiQcN75bhk7gh+ss=
            =vFJJ
            -----END PGP MESSAGE-----
          fp: DDBB778AB55A1D87205700CBDDA211F23723E463
    version: 3.13.3
