apiVersion: v1
kind: Secret
metadata:
    name: vw-rclone-config
    namespace: default
type: Opaque
stringData:
    rclone.conf: ENC[AES256_GCM,data:MnVpuktXPeBgaFYaJZyl8UzgQ83pfC9EjoeJYkIrxtuntmb7dkf1PqyJVG+ryfihOvnaqc5h/ZG+Hw15Ur6ZLvsaAh9gpIW8E4EpKVwADRZORi2YqMdjj2XWCUIsTs/xIkuNORZnqD8Q5pgNUue8Q/KDnx/dB49x/ILHjw8p6MxWP9nLhiRZ7zEOVTN4fVI6Br1QdGtUOewaJRMzzhKr9AKlkWY/8dCuBG1zZrH0FuEbDJKHc9mvMG/TP9ZCbkfK+IYfJ+1ZbGHq5hA4fCi5c49Ucf6J2Ay4NxrZvOel876o2/Uorpd6bYK0rvUKQdBTjj9kW9DGSsnGhGtOyn3brC1UeHlo5KSMls2+LH4pgrIgSvQ=,iv:ZQbqlsal/YuVQFmLa9ZoguMUvA2mLJFuo5XQ0xjpyoo=,tag:JhCJdPqCYIYZMIIWcg6zPA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T16:04:33Z"
    mac: ENC[AES256_GCM,data:Hw7WGCI24ohwtDiYo7YMSFXl4JP/p0PYT9N4w/MBzcOoaaeJEXxBVtNL/AloWCBN2qj02NCpMzzhXw/ncWKCdA0+tI3bnqcdkS2Og+P5nqpgytJP8M+uYMyv8DxcqKJm027Xed50fMH6JkY1j6gaGNMelgRa4Y/tCFboQl/0HS4=,iv:pTH7RftZfgbCetYdguTEHTB2V6Un+FdbyZ1wGO65tNo=,tag:9wR2oVwowF+9XEq5qmZY9A==,type:str]
    pgp:
        - created_at: "2026-09-24T16:04:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9/tRI0Ckh/2ARAA0PMIl+dKasdI2D2+rCg0yg6HVzoskfyMJCwKS4r+4uLR
            91Z6mSRXkhdyP0Ix6r+OZCGkX82r4ClrX6Duj3T+XaDpxeCQs55h2gTdNsPQWdCV
            bThQj8x3/XSZCyqkAdE5PPrCiNQxOEa62bKiG7SGqQ8ITN+O9QRk2kp5eCs3G2T8
            0YQj2qF9Ir0L13LAYopizCInKUf1VOqapQq4gfHsL5cm4Q8SQep8CrYNdjwm67OQ
            0NHSZu8KAeAQ4BYIBOc2cGpB9TCnkouuS32LOA+zRSa5177WnJYgP42WuB2O1rbk
            2aTlpzyavSMtHL3KNV7nZPBjQwhnh3JyLalFYgJftK3ZIKo3M5Is+mLDGkTMYLJB
            zk2O6njDoHclOvD46gmksr1cViqt2VxHqiaCP28C11hPrCK94NBJiMW7AiUfwAVQ
            1L5BTkp+m7ezinsXDyFoHWemoQQsUmfF1+pf6XzAcGxG7l8rWcsL9OOackLfipQl
            YVlp8tYReZAx0OrnNvVZCJf/KJ0pb8wnZAXiOeQMbTJPPYtL1u/I9CYnjzy5T9Cz
            Klr0nqkFkj3im94Zm8G14uyK0n8Bau7wmuMpbj+MtvVNBrZ9dNgdP82CglH8i2Bh
            6mLrzVao8G+w6I2FJZhgGx8XOEKWJeaO8usaEtkJZmhx233vMXV2BRpe8lmkRwDS
            XgFS2bCf9RHLWQLyKnVOs/HdFADXO3mNV94WXWv5CeSypgv7CxW9YH9Lqwmxjive
            Ra4qeVkYi8SAIbq00l0/2JcVJEelceYA1aGS21r2cttOdag9StN79pZmr+0F7yE=
            =+xs8
            -----END PGP MESSAGE-----
          fp: DDBB778AB55A1D87205700CBDDA211F23723E463
    version: 3.13.3
